### ISSUE TITLE
New OSS: NAME

### ISSUE THREAD

**Issue by spiros** [HDRUK/oss#15]
Hi, some repositories I've published which might be relevant:
 
Phenotyping algorithms for biomarkers in UKB primary care https://github.com/spiros/ukb-biomarker-phenotypes
Python module to calculate Frechet distance between curves (for trajectory clustering) https://github.com/spiros/discrete_frechet
Docker containers to run UKB utilities https://github.com/spiros/docker-ukbiobank-utils
Tofu – a tool to generate synethetic UKB data for training and development https://github.com/spiros/tofu
ETL to OMOP CALIBER https://github.com/thehyve/ohdsi-etl-caliber
Phemap – Python library to map ICD10 to Phecodes https://github.com/spiros/phemap
curated list of UKB resources - https://github.com/spiros/ukbiobank-resources

**Comment by susheel** [comment]
Merged
