### ISSUE TITLE
New OSS: NAME

### ISSUE THREAD

**Issue by aidendoherty** [HDRUK/oss#16]
- name: Processing wearable datasets
  url: https://github.com/activityMonitoring/biobankAccelerometerAnalysis
  description: Machine learning of activities of daily living from time-series accelerometer datasets. As used to analyse data from 100,000 UK Biobank participants.
  keywords:
  - accelerometer, machine learning, physical activity, sleep
  categories:
  - Applied Analytics

**Comment by susheel** [comment]
Merged
